
export const THEME_SESSION_NAME = "portfolio-theme";
export const DEFAULT_THEME = "fullape";
export const THEMES_COLLECTION = [
    "aggressive",
    "tinykitten",
    "glassflip",
    "fullape",
    "midplanet",
    "maybeup",
    "coldnight",
    "bored",
    "redwine",
    "simple",
    "light",
    "dark",
    "cyberpunk",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "fantasy",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
    "caramellatte",
    "abyss",
    "silk"
];